<?php
/**
 * Plugin Name:       LZM Lead Button
 * Plugin URI:        https://github.com/valeriagoncalez/lzm-lead-button
 * Description:       Prevent accidental clicks. Add a confirmation form before opening WhatsApp to ensure only real leads are counted.
 * Version:           1.0.0
 * Author:            LZM Digital
 * Author URI:        https://lzmdigital.com.br
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       lzm-lead-button
 * Domain Path:       /languages
 * Requires at least: 6.2
 * Requires PHP:      7.4 
 * 
 * @package         LZMLeadButton
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


/**
 * Register the block and script translations.
 *
 * Registers the Gutenberg block using the metadata from build/block.json
 * and connects the JSON translation files to the editor script.
 *
 * @since 1.0.0
 */
function lzm_register_whatsapp_block() {

	// Registers the block using the metadata in the build directory.
	register_block_type( plugin_dir_path( __FILE__ ) . 'build', array(
        'example' => array(
            'attributes' => array(
                'buttonText' => __( 'WhatsApp', 'lzm-lead-button' ),
				'maxWidth'   => '100px',
                'style'      => array(
                    'color' => array( 
						'background' => '#000000',
                        'text'       => '#ffffff'					
					),
					'border' => array(                        
                        'radius' => '5px', 
                    ),					
					'spacing' => array(                        
                        'padding' => array(
                            'top'    => '15px',
                            'bottom' => '15px',
                            'left'   => '20px',
                            'right'  => '20px',
                        ),
                    ),
                ),				
                'iconVariant' => 'outline',
            ),
        ),
    ));

	// Define the editor script handle explicitly.
	// This must match the handle generated by WordPress for the block.
	$handle = 'lzm-lead-button-editor-script';

	// Load translations for the JavaScript files (Editor).
	if ( wp_script_is( $handle, 'registered' ) ) {
		wp_set_script_translations(
			$handle,
			'lzm-lead-button',
			plugin_dir_path( __FILE__ ) . 'languages'
		);
	}
}
add_action( 'init', 'lzm_register_whatsapp_block' );

